name: Build and push to Docker Hub
on:
  push:
  schedule:
    - cron: '42 2 * * *'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Amsterdam/signals
          ref: master
          fetch-depth: 0

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker build and push
        run: |
          cd api/
          export IMAGE_TAG=$(git describe --tags)
          docker build -t signalen/backend:$IMAGE_TAG .
          docker build -t signalen/backend:latest .
          docker push signalen/backend:$IMAGE_TAG
          docker push signalen/backend:latest

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Amsterdam/signals-frontend
          ref: develop
          fetch-depth: 0

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker build
        run: |
          export IMAGE_TAG=$(git describe --tags)
          docker build -t signalen/frontend:$IMAGE_TAG .
          docker build -t signalen/frontend:latest .
          docker push signalen/frontend:$IMAGE_TAG
          docker push signalen/frontend:latest
