name: Manual build and push tag to Docker Hub
on:
  workflow_dispatch:
    inputs:
      backendTag:
        description: Git tag of the backend
        required: true
      frontendTag:
        description: Git tag of the frontend
        required: true

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Amsterdam/signals
          ref: ${{ github.event.inputs.backendTag }}
          fetch-depth: 0

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker build and push
        run: |
          cd api/
          export IMAGE_TAG=$(git describe --tags)
          docker build -t signalen/backend:$IMAGE_TAG .
          docker build -t signalen/backend:latest .
          docker push signalen/backend:$IMAGE_TAG
          docker push signalen/backend:latest

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Amsterdam/signals-frontend
          ref: ${{ github.event.inputs.frontendTag }}
          fetch-depth: 0

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker build
        run: |
          export IMAGE_TAG=$(git describe --tags)
          docker build -t signalen/frontend:$IMAGE_TAG .
          docker build -t signalen/frontend:latest .
          docker push signalen/frontend:$IMAGE_TAG
          docker push signalen/frontend:latest
